#!/bin/bash

grep_version() {
	echo "$(cat $1 | grep $2 | egrep -Eo "([0-9]{1,}\.)+[0-9]{1,}")"
}

echo "public class VERSION {" > $3
echo "	public static string GodotManager = \"$1\";" >> $3
echo "	public static string GodotSharpExtras = \"$(grep_version $2 GodotSharpExtras)\";" >> $3
echo "	public static string NewtonsoftJSON = \"$(grep_version $2 Newtonsoft.JSON)\";" >> $3
echo "	public static string SystemIOCompression = \"$(grep_version $2 System.IO.Compression)\";" >> $3
echo "	public static string ImageSharp = \"$(grep_version $2 Sixlabors.ImageSharp)\";" >> $3
echo "}" >> $3