name: Create Release
on:
  push:
    tags:
      - 'v*'
  
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version-without-v }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          lfs: true
      - name: Get version name
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version-without-v }}
          body: ""
          draft: true
          prerelease: false
